# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: "Think and Compute: a Primer for Digital Humanists"
author: Silvio Peroni, Ivan Heibi, Arcangelo Massari
logo: logo.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: tac.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Use Author-Year as in-text reference poitner
sphinx:
  extra_extensions:
  config:
    bibtex_reference_style: label
    html_extra_path: ['slides']
  
# Information about where the book exists on the web
repository:
  url: https://github.com/thinkcompute/thinkcompute.github.io  # Online location of your book
  # path_to_book:  # Optional path to your book, relative to the repository root
  # branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
